import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

export default function Home() {
  const router = useRouter();

  const changeRoute = () => {
    if (process.env.NODE_ENV === "production") {
      router.push("https://app.test-multi-domain.vercel.app");
    } else router.push("http://app.localhost:3000");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 onClick={changeRoute}>Move to Test multi domain</h1>
        <h3>{process.env.NODE_ENV}</h3>
      </main>
    </div>
  );
}
